### ISSUE TITLE
Notifications getting later and later

### ISSUE THREAD

**Issue by gabrielaSal** [jclehner/rxdroid#8] opened 2015-11-04 12:21 UTC
On my Galaxy S5 and on a friend's Galaxy Note 4 I've encountered notifications with increasing delays. At the beginning the rxdroid notifications appeared between one and four minutes late. On my phone today it was 28 minutes. For most medication this is no big deal, but I still think it is an issue you should take care of. Is it the database getting "fat"? Is there anything a user can do about that?

**Comment by jclehner** [comment] 2015-11-04 14:28
Are you using any power-saving features/apps on your phone? Or task-killers? The app is configured to wake up the device on the exact time that was specified, but power-saving features can override that, causing an alarm to arrive late.

**Comment by gabrielaSal** [comment] 2015-11-05 09:49
No task-killers or additional power-saving apps installed, didn't play around with power-saving settings.

**Comment by jclehner** [comment] 2015-11-05 10:34
Hmm... thats odd. Do the intervals still keep getting longer?

> Is it the database getting "fat"?

If it were, it should also take the app a long time to start. Also, while 1-4 minutes might explain that, 28 minutes is much too long. In "Settings" -> "Database" you can see how many seconds it took to load the db. What "History size" setting are you using?

Also, which Android version are you and your friend using?

When did you first observe this issue?

**Comment by gabrielaSal** [comment] 2015-11-06 12:21
A delay of 28 minutes occured only once on my own device. Yesterday it was about 8 or 10 minutes, today it was back to 3 minutes again. 
History size (Verlaufsgrösse) is currently set to 2 months. The stats say db has been loaded in 0.168s.
Android version: 5.0. 
I don't know exactly when it started. We've seen delays of two minutes on my friend's device first, starting maybe three or four weeks ago. About one week ago the delays started to occure on my device, too.
On my friend's device it was 4 minutes this morning. He has a Galaxy Note 4, which must be at least Android 5.0 as well.

**Comment by jclehner** [comment] 2015-11-09 18:01
Okay, it appears that there might be in fact a Samsung-specific issue behind this. I've uploaded a new version (0.9.30.9) which *might* address this issue - please report back! The new version will be available via Google Play within the next few hours, but it may also be downloaded [here on github](https://github.com/jclehner/rxdroid/releases/tag/v0.9.30.9).

**Comment by gabrielaSal** [comment] 2015-11-10 14:06
Das Update ist grad reingetrudelt, danke! // Update just arrived on my device, thank you! I'll post again to let you know if this issue is gone. Btw. in the past couple of days the notifiations popped up with 2 - 5 minutes delay only. I could live with that, but 0-1 min would be even better. ;-)

**Comment by jclehner** [comment] 2015-11-10 22:18
I've done a little research and it appears that this is not neccessarily Samsung-specific, but might be caused by a bug in Android ([issue 82001](https://code.google.com/p/android/issues/detail?id=82001)), which was introduced in 5.0 and resolved in 5.0.2. Did you perform a system update to 5.0 shortly before the delays started appearing?

**Comment by gabrielaSal** [comment] 2015-11-11 13:55
That's an interesting finding. But as far as I remember my last system update was a couple of months ago. The delays started occuring some weeks ago (on my device). And what I forgot to mention: I use Samsung's (or is it Google's?) default timer/alarm clock app almost every day. These alarms are exactly on time, although I wouldn't mind if I had several minutes more sleep in the morning.

**Comment by jclehner** [comment] 2015-11-11 14:59
The "alarms" referred to in this issue are a mechanism used by programs such as RxDroid to wake them up at specific times, not the alarm clock app (although this app uses them as well). Are you currently seeing delays of more than a minute?

**Comment by gabrielaSal** [comment] 2015-11-16 16:45
I've watched it for some days now. My friend's Galaxy Note 4 shows delays between 0 and 1 minute now, so this is back to normal. On my own device (Galaxy S5) they are between 2 and 4 minutes.

**Comment by gabrielaSal** [comment] 2015-11-16 16:45
I've watched it for some days now. My friend's Galaxy Note 4 shows delays between 0 and 1 minute now, so this is back to normal. On my own device (Galaxy S5) they are between 2 and 4 minutes.

**Comment by jclehner** [comment] 2015-11-16 16:51
Although I'd expect a delay of a few seconds max, I'd say that 4 minutes is still reasonable, especially compared to 30 minutes or more. Thank you for following up on this, I'm closing it for now, please report back if anything changes.

**Closed by jclehner** 2015-11-16 16:51 UTC
Labels: bug
